
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace OBS.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Absenteeism
{

    public int ID { get; set; }

    public Nullable<int> StudentId { get; set; }

    public string Status { get; set; }

    public Nullable<System.DateTime> Date { get; set; }

    public Nullable<bool> IsFullDay { get; set; }



    public virtual Students Students { get; set; }

}

}
