
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace OBS.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Announcements
{

    public int ID { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public Nullable<bool> AllUser { get; set; }

    public Nullable<System.DateTime> Date { get; set; }

    public Nullable<int> StudentId { get; set; }

    public Nullable<int> ClassId { get; set; }

    public Nullable<int> LessonId { get; set; }

    public Nullable<int> CreatedBy { get; set; }



    public virtual Classes Classes { get; set; }

    public virtual Lesson Lesson { get; set; }

    public virtual Students Students { get; set; }

}

}
