
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace OBS.Models
{

using System;
    using System.Collections.Generic;
    
public partial class ClassSchedule
{

    public int ID { get; set; }

    public Nullable<int> ClassId { get; set; }

    public Nullable<int> LessonId { get; set; }

    public string Day { get; set; }

    public string StartTime { get; set; }

    public string EndTime { get; set; }

    public string Color { get; set; }

}

}
