
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace OBS.Models
{

using System;
    using System.Collections.Generic;
    
public partial class ClassStudents
{

    public int ID { get; set; }

    public Nullable<int> ClassId { get; set; }

    public Nullable<int> StudentID { get; set; }

    public Nullable<System.DateTime> CreatedDate { get; set; }

    public Nullable<System.DateTime> ModifiedDate { get; set; }



    public virtual Classes Classes { get; set; }

    public virtual Students Students { get; set; }

}

}
