
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace OBS.Models
{

using System;
    using System.Collections.Generic;
    
public partial class ClassLessons
{

    public int ID { get; set; }

    public Nullable<int> ClassID { get; set; }

    public Nullable<int> LessonID { get; set; }



    public virtual Classes Classes { get; set; }

    public virtual Lesson Lesson { get; set; }

}

}
