

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace OBS.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class OBSEntities : DbContext
{
    public OBSEntities()
        : base("name=OBSEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Classes> Classes { get; set; }

    public virtual DbSet<ClassLessons> ClassLessons { get; set; }

    public virtual DbSet<ClassStudents> ClassStudents { get; set; }

    public virtual DbSet<Lesson> Lesson { get; set; }

    public virtual DbSet<Notes> Notes { get; set; }

    public virtual DbSet<Professions> Professions { get; set; }

    public virtual DbSet<Users> Users { get; set; }

    public virtual DbSet<Students> Students { get; set; }

    public virtual DbSet<Teachers> Teachers { get; set; }

    public virtual DbSet<ClassSchedule> ClassSchedule { get; set; }

    public virtual DbSet<Announcements> Announcements { get; set; }

    public virtual DbSet<HomeWork> HomeWork { get; set; }

}

}

